
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JT-Produções
 */
public class Principal extends javax.swing.JFrame implements QuardaVagas{

    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        b_menu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        b_pesquisar = new javax.swing.JMenuItem();
        b_Listar = new javax.swing.JMenuItem();
        b_editar = new javax.swing.JMenuItem();
        b_renovar = new javax.swing.JMenuItem();
        b_remover = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        b_sair = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        b_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/book_go.png"))); // NOI18N
        b_menu.setText("Menu");
        b_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_menuActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jMenuItem1.setText("Cadastrar Anuncio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        b_menu.add(jMenuItem1);

        b_pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/magnifier.png"))); // NOI18N
        b_pesquisar.setText("Pesquisar por vagas de emprego");
        b_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_pesquisarActionPerformed(evt);
            }
        });
        b_menu.add(b_pesquisar);

        b_Listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/book_open.png"))); // NOI18N
        b_Listar.setText("Listar Anuncios");
        b_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ListarActionPerformed(evt);
            }
        });
        b_menu.add(b_Listar);

        b_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mouse.png"))); // NOI18N
        b_editar.setText("Editar Anuncio");
        b_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_editarActionPerformed(evt);
            }
        });
        b_menu.add(b_editar);

        b_renovar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        b_renovar.setText("Renovar anuncio");
        b_renovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_renovarActionPerformed(evt);
            }
        });
        b_menu.add(b_renovar);

        b_remover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete.png"))); // NOI18N
        b_remover.setText("Remover anuncio");
        b_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_removerActionPerformed(evt);
            }
        });
        b_menu.add(b_remover);

        jMenuBar1.add(b_menu);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        jMenu2.setText("login");
        jMenuBar1.add(jMenu2);

        b_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/book_open.png"))); // NOI18N
        b_sair.setText("sobre");
        jMenuBar1.add(b_sair);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_delete.png"))); // NOI18N
        jMenu1.setText("sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_menuActionPerformed

    }//GEN-LAST:event_b_menuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        TelaCadastrar telaCad = new TelaCadastrar();                                                                            
        jDesktopPane1.add(telaCad);
        telaCad.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
    
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        JOptionPane.showMessageDialog(null,"Obrigado por usar nosso programa "); 
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void b_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_pesquisarActionPerformed
        if(!listadevagas.isEmpty()){
        TelaPesquisa telapesq = new TelaPesquisa();
        jDesktopPane1.add(telapesq);
        telapesq.setVisible(true);
        }else{
        JOptionPane.showMessageDialog(null,"Erro!! ainda não existem vagas cadastradas, selecione no menu a opção de cadastrar vagas");
        }
    }//GEN-LAST:event_b_pesquisarActionPerformed

    private void b_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ListarActionPerformed
        if(!listadevagas.isEmpty()){
        TelaListar telalist = new TelaListar();
         jDesktopPane1.add(telalist);
         telalist.setVisible(true);
        }else{
        JOptionPane.showMessageDialog(null,"Erro!! ainda não existem anuncios cadastradas, selecione no menu a opção de cadastrar vagas");
        }
    }//GEN-LAST:event_b_ListarActionPerformed

    private void b_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_editarActionPerformed
        if(!listadevagas.isEmpty()){
        TelaEdit telaedit = new TelaEdit();
        jDesktopPane1.add(telaedit);
        telaedit.setVisible(true);
        }else{
        JOptionPane.showMessageDialog(null,"Erro!! ainda não existem anuncios cadastradas, selecione no menu a opção de cadastrar vagas");
        }
    }//GEN-LAST:event_b_editarActionPerformed

    private void b_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_removerActionPerformed
        if(!listadevagas.isEmpty()){
        TelaRemover telaremov = new TelaRemover();
        jDesktopPane1.add(telaremov);
        telaremov.setVisible(true);
        }else{
        JOptionPane.showMessageDialog(null,"Erro!! ainda não existem anuncios cadastradas, selecione no menu a opção de cadastrar vagas");
        }
    }//GEN-LAST:event_b_removerActionPerformed

    private void b_renovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_renovarActionPerformed
       if(!listadevagas.isEmpty()){
        TelaRenovar telareno = new TelaRenovar();
        jDesktopPane1.add(telareno);
        telareno.setVisible(true);
       }else{
        JOptionPane.showMessageDialog(null,"Erro!! ainda não existem anuncios cadastradas, selecione no menu a opção de cadastrar vagas");
        }
    }//GEN-LAST:event_b_renovarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem b_Listar;
    private javax.swing.JMenuItem b_editar;
    private javax.swing.JMenu b_menu;
    private javax.swing.JMenuItem b_pesquisar;
    private javax.swing.JMenuItem b_remover;
    private javax.swing.JMenuItem b_renovar;
    private javax.swing.JMenu b_sair;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
