
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JT-Produções
 */
public class TelaEdit extends javax.swing.JInternalFrame implements QuardaVagas{
    private int index;
    private boolean condi=false;
  
    public TelaEdit() {
        initComponents();
        for(int i=0;i<listadevagas.size();i++){
         combo_editpar.addItem(listadevagas.get(i).getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        in_nomeFuncao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        in_areaAtu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        in_descriArea = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        in_enpresa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        in_anodeFunda = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        in_ramoemp = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        in_regime = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        in_descriRegime = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        in_jornada = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        in_quantidadeVagas = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        in_remunera = new javax.swing.JTextField();
        b_submitCad = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        combo_editpar = new javax.swing.JComboBox<>();
        b_edit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);

        jLabel8.setText("Digite o nome da fução: ");

        jLabel9.setText("Digite a area de atuação: ");

        jLabel10.setText("Digite a descrição da area de atuação: ");

        jLabel11.setText("Digite a empresa da vaga: ");

        jLabel12.setText("Digite o ano da fundação da empresa:");

        jLabel13.setText("Digite o ramo da empresa da vaga: ");

        jLabel14.setText("Digite a opção de regime de contratação (CLT ou PJ): ");

        jLabel15.setText("Digite a descrição do regime: ");

        jLabel16.setText("Digite a jornada de trabalho (Em horas semanais) :");

        jLabel17.setText("Digite a quantidade de vagas:");

        jLabel18.setText("Digite a remuneração:");

        b_submitCad.setText("Finalizar edição");
        b_submitCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_submitCadActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Edição de Anuncios");

        jLabel1.setText("Selecione qual anuncio voce quer editar");

        b_edit.setText("Edit");
        b_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_editActionPerformed(evt);
            }
        });

        jLabel3.setText("Em seguida corrija o campo que quer editar ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel15))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(b_submitCad))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel16))
                                .addComponent(in_anodeFunda, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                .addComponent(in_ramoemp)
                                .addComponent(in_regime)
                                .addComponent(jLabel14)
                                .addComponent(in_descriRegime)
                                .addComponent(in_jornada)
                                .addComponent(in_quantidadeVagas)
                                .addComponent(in_remunera)
                                .addComponent(in_descriArea)
                                .addComponent(in_enpresa)
                                .addComponent(in_areaAtu)
                                .addComponent(in_nomeFuncao))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(b_edit))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(combo_editpar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel18)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combo_editpar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(b_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_nomeFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_areaAtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_descriArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_enpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_anodeFunda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_ramoemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_regime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_descriRegime, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(in_jornada, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(in_quantidadeVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_remunera, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_submitCad)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_submitCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_submitCadActionPerformed
        
        if(condi && ! in_nomeFuncao.getText().isEmpty()){
        listadevagas.get(index).setNome(in_nomeFuncao.getText());
        listadevagas.get(index).setArea(in_areaAtu.getText());
        listadevagas.get(index).setDescricaoare(in_descriArea.getText());
        listadevagas.get(index).setNomedaemp(in_enpresa.getText());
        listadevagas.get(index).setAno(in_anodeFunda.getText());
        listadevagas.get(index).setRamo(in_ramoemp.getText());
        listadevagas.get(index).setRegime(in_regime.getText());
        listadevagas.get(index).setDescricaoregi(in_descriRegime.getText());
        listadevagas.get(index).setJornada(in_jornada.getText());
        listadevagas.get(index).setJornada(in_jornada.getText());
        listadevagas.get(index).setRemunera(in_remunera.getText());
        condi=false;
        combo_editpar.removeAllItems();
        for(int i=0;i<listadevagas.size();i++){
        combo_editpar.addItem(listadevagas.get(i).getNome());
        }
        in_nomeFuncao.setText("");
        in_areaAtu.setText("");
        in_descriArea.setText("");
        in_enpresa.setText("");
        in_anodeFunda.setText("");
        in_ramoemp.setText("");
        in_regime.setText("");
        in_descriRegime.setText("");
        in_jornada.setText("");
        in_quantidadeVagas.setText("");
        in_remunera.setText("");
        JOptionPane.showMessageDialog(null,"Editado com sucesso\n Selecione outra vaga e clique em edit para eidtar mais \n Ou feche a janela para ecerrar as edições ");
        }else{
        JOptionPane.showMessageDialog(null,"Selecione um anuncio e clique em edit");
        
        }
        
        
    }//GEN-LAST:event_b_submitCadActionPerformed

    private void b_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_editActionPerformed
        index=combo_editpar.getSelectedIndex();
        in_nomeFuncao.setText(listadevagas.get(index).getNome());
        in_areaAtu.setText(listadevagas.get(index).getArea());
        in_descriArea.setText(listadevagas.get(index).getDescricaoare());
        in_enpresa.setText(listadevagas.get(index).getNomedaemp());
        in_anodeFunda.setText(listadevagas.get(index).getAno());
        in_ramoemp.setText(listadevagas.get(index).getRamo());
        in_regime.setText(listadevagas.get(index).getRegime());
        in_descriRegime.setText(listadevagas.get(index).getDescricaoregi());
        in_jornada.setText(listadevagas.get(index).getJornada());
        in_quantidadeVagas.setText(listadevagas.get(index).getJornada());
        in_remunera.setText(listadevagas.get(index).getRemunera());
        this.condi=true;
    }//GEN-LAST:event_b_editActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_edit;
    private javax.swing.JButton b_submitCad;
    private javax.swing.JComboBox<String> combo_editpar;
    private javax.swing.JTextField in_anodeFunda;
    private javax.swing.JTextField in_areaAtu;
    private javax.swing.JTextField in_descriArea;
    private javax.swing.JTextField in_descriRegime;
    private javax.swing.JTextField in_enpresa;
    private javax.swing.JTextField in_jornada;
    private javax.swing.JTextField in_nomeFuncao;
    private javax.swing.JTextField in_quantidadeVagas;
    private javax.swing.JTextField in_ramoemp;
    private javax.swing.JTextField in_regime;
    private javax.swing.JTextField in_remunera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
