
import javax.swing.JOptionPane;


public class TelaCadastrar extends javax.swing.JInternalFrame implements QuardaVagas{

    public TelaCadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        r_azul = new javax.swing.JRadioButton();
        r_bronze = new javax.swing.JRadioButton();
        r_prata = new javax.swing.JRadioButton();
        r_ouro = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        in_dataini = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        in_nomeFuncao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        in_areaAtu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        in_descriArea = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        in_enpresa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        in_anodeFunda = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        in_ramoemp = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        in_regime = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        in_descriRegime = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        in_jornada = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        in_quantidadeVagas = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        in_remunera = new javax.swing.JTextField();
        b_submitCad = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Myriad Pro Light", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Anuncio:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selecione o tipo de anuncio");

        jLabel3.setText("Azul: valor = Gratuito, 2 dias de duração, não adimite renovação");

        jLabel4.setText("Bronze: valor=R$50,00 , 7 dias de duração, adimite 1 renovação");

        jLabel5.setText("Prata: valor = R$70,00 , 15 dias de duração, adimite 2 renovações");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Ouro: valor=100, 30 dias de duração, adimite 3 renovações");

        buttonGroup1.add(r_azul);
        r_azul.setText("Azul");

        buttonGroup1.add(r_bronze);
        r_bronze.setText("Bronze");

        buttonGroup1.add(r_prata);
        r_prata.setText("Prata");

        buttonGroup1.add(r_ouro);
        r_ouro.setText("Ouro");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Digite a data de inicio do anuncio: dd/mm/a: ");

        jLabel8.setText("Digite o nome da função: ");

        jLabel9.setText("Digite a area de atuação: ");

        jLabel10.setText("Digite a descrição da area de atuação: ");

        jLabel11.setText("Digite a empresa da vaga: ");

        jLabel12.setText("Digite o ano da fundação da empresa:");

        jLabel13.setText("Digite o ramo da empresa da vaga: ");

        jLabel14.setText("Digite a opção de regime de contratação (CLT ou PJ): ");

        jLabel15.setText("Digite a descrição do regime: ");

        jLabel16.setText("Digite a jornada de trabalho (Em horas semanais) :");

        jLabel17.setText("Digite a quantidade de vagas:");

        jLabel18.setText("Digite a remuneração:");

        b_submitCad.setText("Cadastrar");
        b_submitCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_submitCadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(r_azul))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(r_prata)
                                    .addComponent(r_bronze)
                                    .addComponent(r_ouro)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel8))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel17))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel15))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel16))
                                .addComponent(in_anodeFunda, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                .addComponent(in_ramoemp)
                                .addComponent(in_regime)
                                .addComponent(jLabel14)
                                .addComponent(in_descriRegime)
                                .addComponent(in_jornada)
                                .addComponent(in_quantidadeVagas)
                                .addComponent(in_remunera)
                                .addComponent(in_descriArea)
                                .addComponent(in_enpresa)
                                .addComponent(in_areaAtu)
                                .addComponent(in_nomeFuncao)
                                .addComponent(in_dataini))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(b_submitCad)))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r_azul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r_bronze)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r_prata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r_ouro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_dataini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_nomeFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_areaAtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_descriArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_enpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_anodeFunda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_ramoemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_regime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_descriRegime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(in_jornada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_quantidadeVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(in_remunera, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_submitCad)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_submitCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_submitCadActionPerformed
        int tipo=0;
        int dia=0;
        int mes=0;
        int ano=0;
        String inicio=in_dataini.getText();
        if(!inicio.isEmpty()){
        String[] data=inicio.split("/");
        dia= Integer.parseInt(data[0]);
         mes= Integer.parseInt(data[1]);
         ano= Integer.parseInt(data[2]);
        }
        String nome=in_nomeFuncao.getText();
        String area=in_areaAtu.getText();
        String descript=in_descriArea.getText();
        String nomedaemp=in_enpresa.getText();
        String anodeFundacao=in_anodeFunda.getText();
        String ramo=in_ramoemp.getText();
        String regime=in_regime.getText();
        String descrire=in_descriRegime.getText();
        String jornada=in_jornada.getText();
        String vagas=in_quantidadeVagas.getText();
        String remuneracao=in_remunera.getText();
        
        if(!r_azul.isSelected()&&!r_bronze.isSelected()&&!r_prata.isSelected()&&!r_ouro.isSelected()){
        JOptionPane.showMessageDialog(null,"Selecione um Tipo de anuncio");
        }else if(inicio.isEmpty()){
        JOptionPane.showMessageDialog(null,"Prencha o campo ->Data inicio");    
        }else if(nome.isEmpty()){
        JOptionPane.showMessageDialog(null,"Prencha o campo ->Nome da função"); 
        }else if(area.isEmpty()){
        JOptionPane.showMessageDialog(null,"Prencha o campo ->Area de atuação"); 
        }else if(descript.isEmpty()){
        JOptionPane.showMessageDialog(null,"Prencha o campo ->Descrição da area de atuação"); 
        }else if(nomedaemp.isEmpty()){
        JOptionPane.showMessageDialog(null,"Prencha o campo ->Nome da empresa"); 
        }else if(anodeFundacao.isEmpty()){
        JOptionPane.showMessageDialog(null,"Prencha o campo ->Ano de fundação da empresa"); 
        }else if(ramo.isEmpty()){
        JOptionPane.showMessageDialog(null,"Prencha o campo ->Ramo da empresa"); 
        }else if(regime.isEmpty()){
        JOptionPane.showMessageDialog(null,"Prencha o campo ->Regime de contratação"); 
        }else if(descrire.isEmpty()){
        JOptionPane.showMessageDialog(null,"Prencha o campo ->Descrição do Regime"); 
        }else if(jornada.isEmpty()){
        JOptionPane.showMessageDialog(null,"Prencha o campo ->Jornada de trabalho"); 
        }else if(vagas.isEmpty()){
        JOptionPane.showMessageDialog(null,"Prencha o campo ->Quantidade de vagas"); 
        }else if(remuneracao.isEmpty()){
        JOptionPane.showMessageDialog(null,"Prencha o campo ->Remuneração"); 
        }else {
            if(r_azul.isSelected()){
            tipo=0;
            }else if(r_bronze.isSelected()){
            tipo=1;
            }else if(r_prata.isSelected()){
            tipo=2;
            }else if(r_ouro.isSelected()){
            tipo=3;
            }
        Areadeatuacao Atuacao = new Areadeatuacao(nome,area,descript);
        EmpresadaVaga Empresa = new EmpresadaVaga(nomedaemp,anodeFundacao,ramo);
        Regimedecontratacao Regime = new  Regimedecontratacao(regime, descrire); 
        Tipos Tipoa = new Tipos(tipo, dia,  mes,  ano);
        Vaga vaga = new Vaga(Atuacao, Empresa, Regime, Tipoa,jornada, vagas, remuneracao);
        //adiciona ao arraylist
        
        listadevagas.add(vaga);
        //limpa campos
        buttonGroup1.clearSelection();
        in_dataini.setText("");
        in_nomeFuncao.setText("");
        in_areaAtu.setText("");
        in_descriArea.setText("");
        in_enpresa.setText("");
        in_anodeFunda.setText("");
        in_ramoemp.setText("");
        in_regime.setText("");
        in_descriRegime.setText("");
        in_jornada.setText("");
        in_quantidadeVagas.setText("");
        in_remunera.setText("");
        JOptionPane.showMessageDialog(null,"Cadastrado com Sucesso\n"+"Efetue um novo dadasto\n"+"Ou se desejar encerrar os cadastros é só fechar a tela"); 
       
        }
    }//GEN-LAST:event_b_submitCadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_submitCad;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JTextField in_anodeFunda;
    private javax.swing.JTextField in_areaAtu;
    private javax.swing.JTextField in_dataini;
    private javax.swing.JTextField in_descriArea;
    private javax.swing.JTextField in_descriRegime;
    private javax.swing.JTextField in_enpresa;
    private javax.swing.JTextField in_jornada;
    private javax.swing.JTextField in_nomeFuncao;
    private javax.swing.JTextField in_quantidadeVagas;
    private javax.swing.JTextField in_ramoemp;
    private javax.swing.JTextField in_regime;
    private javax.swing.JTextField in_remunera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton r_azul;
    private javax.swing.JRadioButton r_bronze;
    private javax.swing.JRadioButton r_ouro;
    private javax.swing.JRadioButton r_prata;
    // End of variables declaration//GEN-END:variables
}
