/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JT-Produções
 */
public class TelaListar extends javax.swing.JInternalFrame implements QuardaVagas {

    /**
     * Creates new form TelaListar
     */
    public TelaListar() {
        initComponents();
        for(int i=0;i<listadevagas.size();i++){
        txt_lista.append(listadevagas.get(i).getNome()+"\n"+"Remuneração :"+
                listadevagas.get(i).getRemunera()+"\n"+"Na empresa: "+listadevagas.get(i).getNomedaemp()+"\n \n");
         combo_vagas.addItem(listadevagas.get(i).getNome());
        }
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_lista = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combo_vagas = new javax.swing.JComboBox<>();
        b_saiba = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_sabermais = new javax.swing.JTextArea();

        setClosable(true);

        txt_lista.setColumns(20);
        txt_lista.setRows(5);
        jScrollPane1.setViewportView(txt_lista);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Lista de Anuncios");

        jLabel2.setText("Quer saber mais sobre uma vaga? Selcione abaixo qual vaga você quer saber mais ");

        b_saiba.setText("Saiber mais");
        b_saiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_saibaActionPerformed(evt);
            }
        });

        txt_sabermais.setColumns(20);
        txt_sabermais.setRows(5);
        jScrollPane2.setViewportView(txt_sabermais);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(121, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2))
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_vagas, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(b_saiba)
                                .addGap(21, 21, 21)))
                        .addGap(233, 233, 233))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_vagas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_saiba)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_saibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_saibaActionPerformed
        int index=combo_vagas.getSelectedIndex();
        txt_sabermais.setText("Nome da função: "+listadevagas.get(index).getNome()+"\n Tipo de Azuncio: "+listadevagas.get(index).getTipo()+"\n Data de inicio do Anuncio: "+listadevagas.get(index).getDataini()+"\n Data final do anuncio: "+listadevagas.get(index).getDatafim()+"\n"+"Area de atuação: "+
                listadevagas.get(index).getArea()+"\n"+"Descrição da area "+listadevagas.get(index).getDescricaoare()+"\n"
                +"Nome da empresa da vaga: "+listadevagas.get(index).getNomedaemp()+"\n"+"Ano de fundação da empresa: "+
                listadevagas.get(index).getAno()+"\n"+"Ramo da empresa: "+listadevagas.get(index).getRamo()+"\n"+"Regime de contratação: "+
                listadevagas.get(index).getRegime()+"\n"+"Descrição do regime: "+listadevagas.get(index).getDescricaoregi()+"\n"+
                "Jornada de trabalho: "+listadevagas.get(index).getJornada()+"\n"+"Quantidade de vagas: "+listadevagas.get(index).getVagas()+"\n"+
                "Remuneração: "+listadevagas.get(index).getRemunera());
    }//GEN-LAST:event_b_saibaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_saiba;
    private javax.swing.JComboBox<String> combo_vagas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_lista;
    private javax.swing.JTextArea txt_sabermais;
    // End of variables declaration//GEN-END:variables
}
